# Connection and login limits

# Max connections per user (across all IPs)
mail_max_userip_connections = 20

# Disconnect idle IMAP connections after 30 minutes
imap_idle_notify_interval = 2 mins

# Login process: kill after 60s if authentication not completed
auth_failure_delay = 2 secs
