# Service definitions
service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
  process_min_avail = 2
  process_limit = 128
}

service imap {
  process_limit = 256       # max concurrent authenticated IMAP sessions
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = ulaknode-mail
  }
  unix_listener auth-userdb {
    mode = 0600
    user = postfix
  }
}

service auth-worker {
}