# Core configuration file - only includes and version should be here.

dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0
listen = *
protocols = imap lmtp

log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot.log
debug_log_path = /var/log/dovecot.log

# Include all necessary configuration files from conf.d
!include_try /etc/dovecot/conf.d/*.conf